// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Ghostly.Data.Migrations
{
    public partial class ProfileMigration : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "Identifier",
                table: "Rules",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "ImportedAt",
                table: "Rules",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "ImportedFrom",
                table: "Rules",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Identifier",
                table: "Categories",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "ImportedAt",
                table: "Categories",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "ImportedFrom",
                table: "Categories",
                nullable: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Identifier",
                table: "Rules");

            migrationBuilder.DropColumn(
                name: "ImportedAt",
                table: "Rules");

            migrationBuilder.DropColumn(
                name: "ImportedFrom",
                table: "Rules");

            migrationBuilder.DropColumn(
                name: "Identifier",
                table: "Categories");

            migrationBuilder.DropColumn(
                name: "ImportedAt",
                table: "Categories");

            migrationBuilder.DropColumn(
                name: "ImportedFrom",
                table: "Categories");
        }
    }
}
